### ISSUE TITLE
最近的几个Koolss貌似有些总有些问题？？

### ISSUE THREAD

**Issue by huxuansong** [koolshare/ledesoft#125]
可以确认我自己架设的Kcptun+SS服务器（自用的）没有任何问题，
因为使用手机SS客户端和电脑客户端，翻墙都没有问题！

但是LEDE上的koolss却不定时的无法翻墙，而此时使用电脑或手机客户端无任何问题
两周前，尝试退回到koolss 2.0.0之后，这两周LEDE再也没有出现无法翻墙的问题，终于一切正常了

难道是新版本的问题？？

**Comment by huxuansong** [comment]
补充一下，我没有安装其他软件中心的软件，只有安装Koolss

**Comment by syuraking** [comment]
这问题好久了，2.0.4之前都是正常的，自从2.0.5改了DNS解析方式后，就开始异常了，
DNS时不时会随机崩溃，都是无解状态。

我一直就没更新插件了……保持2.0.4状态了

**Comment by xiangzl64** [comment]
确实如此，我的LEDE老出问题，但是在我梅林路由器上的一切正常。

**Comment by huxuansong** [comment]
> 这问题好久了，2.0.4之前都是正常的，自从2.0.5改了DNS解析方式后，就开始异常了，
> DNS时不时会随机崩溃，都是无解状态。
> 
> 我一直就没更新插件了……保持2.0.4状态了

请问一下能不能发一份2.0.4的离线包呢？我的邮箱 hxs#live.com，请将#改@，万分感谢

**Comment by betwowt** [comment]
> > 这问题好久了，2.0.4之前都是正常的，自从2.0.5改了DNS解析方式后，就开始异常了，
> > DNS时不时会随机崩溃，都是无解状态。
> > 我一直就没更新插件了……保持2.0.4状态了
> 
> 请问一下能不能发一份2.0.4的离线包呢？我的邮箱 hxs#live.com，请将#改@，万分感谢

同求 2.0.4版本   邮箱 betwowt#gmail.com

**Comment by syuraking** [comment]
我有留存，已经发给二位

**Comment by ripcity32** [comment]
ripmyself32@gmail.com 同求，谢谢

**Comment by huxuansong** [comment]
> 我有留存，已经发给二位

非常感谢，已经收到

**Comment by fineemb** [comment]
> 我有留存，已经发给二位

同求2.0.4 embont&gmail.com 谢谢

**Comment by rsnowcn** [comment]
请问LEDE koolshare 2.3版本中SSR+KCP这个怎么设置，我看服务器端的KCP好像没见到，有打包的服务器端安装程序吗？求，万分感谢！^^

**Comment by rsnowcn** [comment]
> 我有留存，已经发给二位

同求 rs@rsnow.cn

**Comment by rsnowcn** [comment]
> 我有留存，已经发给二位

同求，万分感谢！ rs&rsnow.cn

**Comment by maiduyaode** [comment]
> 我有留存，已经发给二位

同求，maiduyaode@gmail.com
感谢！

**Comment by ripcity32** [comment]
还好吧，我是lede2.30+koolss2.2.2，稳定的。发自我的iPhone------------------ 原始邮件 ------------------发件人: maiduyaode  <notifications@github.com>发送时间: 2019年4月5日 12:40收件人: koolshare/ledesoft <ledesoft@noreply.github.com>抄送: ripcity32 <ripmyself32@gmail.com>, Comment <comment@noreply.github.com>主题: 回复：[koolshare/ledesoft] 最近的几个Koolss貌似有些总有些问题？？ (#125)
我有留存，已经发给二位

同求，maiduyaode@gmail.com
感谢！

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/koolshare/ledesoft","title":"koolshare/ledesoft","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/koolshare/ledesoft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maiduyaode in #125: \u003e 我有留存，已经发给二位\r\n\r\n同求，maiduyaode@gmail.com\r\n感谢！"}],"action":{"name":"View Issue","url":"https://github.com/koolshare/ledesoft/issues/125#issuecomment-480146011"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/koolshare/ledesoft/issues/125#issuecomment-480146011",
"url": "https://github.com/koolshare/ledesoft/issues/125#issuecomment-480146011",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ripcity32** [comment]
maiduyaode <notifications@github.com>于2019年4月5日 周五12:40写道：

**Comment by raighneweng** [comment]
@syuraking 麻烦发一份crazywh@live.com,谢谢

**Comment by voidAlex** [comment]
> 我有留存，已经发给二位

求个2.04版本的 谢谢 wangld1994#gmail.com
